services:
  api_gateway: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: always
    ports:
      - "5000:5000"
    networks:
      - my-network

networks: 
  my-network:
    driver: bridge
    external: true # to use an external network. Need to create the network first with a command
