services:
  videogame_service: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${VIDEOGAME_SERVICE_NAME}
    restart: always
    networks:
      - gameradar-network
    depends_on:
      - db
  db:
    image: postgres
    container_name: ${VIDEOGAME_DB_CONTAINER_NAME}
    restart: always
    ports:
      - "7500:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - videogame_pgdata:/var/lib/postgresql/data
    networks:
      - gameradar-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: ${VIDEOGAME_PGADMIN_NAME}
    restart: unless-stopped
    ports:
      - "7080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - videogame_pgadmin-data:/var/lib/pgadmin
    networks:
      - gameradar-network
    depends_on:
      - db

volumes:
  videogame_pgdata:
  videogame_pgadmin-data:

networks: 
  gameradar-network:
    driver: bridge
    external: true # to use an external network. Need to create the network first with a command
