services:
  videogame_service: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: videogame_service
    restart: always
    networks:
      - gameradar-network
    depends_on:
      - db
  db:
    image: postgres
    container_name: videogame_pgdb
    restart: always
    ports:
      - "7500:5432"
    environment:
      POSTGRES_USER: Us3rn4me
      POSTGRES_PASSWORD: Passw0rd
    volumes:
      - videogame_pgdata:/var/lib/postgresql/data
    networks:
      - gameradar-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: videogame_pgadmin
    restart: unless-stopped
    ports:
      - "7080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: Passw0rd
    volumes:
      - videogame_pgadmin-data:/var/lib/pgadmin
    networks:
      - gameradar-network
    depends_on:
      - db

volumes:
  videogame_pgdata:
  videogame_pgadmin-data:

networks: 
  gameradar-network:
    driver: bridge
    external: true # to use an external network. Need to create the network first with a command
