openapi: 3.0.0
info:
  title: Videogame API
  description: API for managing videogames, user lists, reviews, and wishlist
  version: 1.0.0

servers:
  - url: http://localhost:4000
    description: Local server

paths:
  /videogame/games:
    get:
      summary: Get paginated videogames
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Games fetched successfully
        '404':
          description: No games found

  /videogame/games/search:
    get:
      summary: Search games by name
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Games fetched successfully
        '400':
          description: Name is required

  /videogame/games/details/{appid}:
    get:
      summary: Get Steam game details by AppID
      parameters:
        - name: appid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Game fetched successfully
        '400':
          description: Appid is required
        '404':
          description: Game not found

  /videogame/games/review:
    post:
      summary: Add a review
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewInput'
      responses:
        '200':
          description: Review added successfully
        '400':
          description: Some fields are missing
        '401':
          description: Unauthorized
        '409':
          description: Already reviewed

  /videogame/games/review/{gameId}:
    get:
      summary: Get reviews for a game
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reviews fetched successfully
        '400':
          description: GameId is required

  /videogame/gamelists:
    get:
      summary: Get gamelists (global)
      responses:
        '200':
          description: Gamelists fetched successfully

  /videogame/gamelists/add:
    post:
      summary: Add game to a user's list
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddGameInput'
      responses:
        '200':
          description: Game added to list
        '401':
          description: Unauthorized
        '409':
          description: Game already in list

  /videogame/wishlist:
    get:
      summary: Get user wishlist
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Wishlist fetched successfully
        '401':
          description: Unauthorized
        '404':
          description: Wishlist not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ReviewInput:
      type: object
      required:
        - gameId
        - name
        - rating
        - review
      properties:
        gameId:
          type: string
        name:
          type: string
        rating:
          type: integer
        review:
          type: string

    AddGameInput:
      type: object
      required:
        - gameId
        - name
      properties:
        gameId:
          type: string
        name:
          type: string
