openapi: 3.0.3
info:
  title: Game API
  description: API for managing games, reviews, and wishlists
  version: 1.0.0

servers:
  - url: http://localhost:4000/videogame

tags:
  - name: Reviews
  - name: Games
  - name: Wishlist

paths:
  /reviews/{gameId}:
    get:
      tags: [Reviews]
      summary: Get reviews for a specific game
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: List of reviews retrieved
        400:
          description: Missing gameId

  /reviews:
    post:
      tags: [Reviews]
      summary: Add a review for a game
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [gameId, name, rating, review]
              properties:
                gameId:
                  type: integer
                name:
                  type: string
                rating:
                  type: number
                review:
                  type: string
      responses:
        200:
          description: Review added successfully
        400:
          description: Missing fields
        401:
          description: Unauthorized
        409:
          description: Already reviewed

  /games:
    get:
      tags: [Games]
      summary: Get a list of games
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: limit
          in: query
          schema:
            type: integer
      responses:
        200:
          description: List of games retrieved
        404:
          description: No games found

  /games/details/{appid}:
    get:
      tags: [Games]
      summary: Get game details by Steam appid
      parameters:
        - name: appid
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Game details retrieved
        400:
          description: Missing appid
        404:
          description: Game not found

  /games/search:
    get:
      tags: [Games]
      summary: Search for games by name
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Search results
        400:
          description: Name is required

  /wishlist:
    post:
      tags: [Wishlist]
      summary: Add a game to the wishlist
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [gameId, name]
              properties:
                gameId:
                  type: integer
                name:
                  type: string
      responses:
        200:
          description: Game successfully added
        401:
          description: Unauthorized
        409:
          description: Game already in the list

  /wishlist/my:
    get:
      tags: [Wishlist]
      summary: Get the authenticated user's wishlist
      security:
        - bearerAuth: []
      responses:
        200:
          description: Wishlist retrieved
        401:
          description: Unauthorized
        404:
          description: Wishlist not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
