services:
  user_service: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service
    restart: always
    # ports:
    #   - "5000:5000"
    networks:
      - gameradar-network
    depends_on:
      - db
  db:
    image: postgres
    container_name: user_pgdb
    restart: always
    ports:
      - "5500:5432"
    environment:
      POSTGRES_USER: Us3rn4me
      POSTGRES_PASSWORD: Passw0rd
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    networks:
      - gameradar-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: user_pgadmin
    restart: unless-stopped
    ports:
      - "5080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: Passw0rd
    volumes:
      - user_pgadmin-data:/var/lib/pgadmin
    networks:
      - gameradar-network
    depends_on:
      - db

volumes:
  user_pgdata:
  user_pgadmin-data:

networks: 
  gameradar-network:
    driver: bridge
    external: true # to use an external network
