services:
  user_service: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${USER_SERVICE_NAME}
    restart: always
    networks:
      - gameradar-network
    depends_on:
      - db
  db:
    image: postgres
    container_name: ${USER_DB_CONTAINER_NAME}
    restart: always
    ports:
      - "5500:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    networks:
      - gameradar-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: ${USER_PGADMIN_NAME}
    restart: unless-stopped
    ports:
      - "5080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - user_pgadmin-data:/var/lib/pgadmin
    networks:
      - gameradar-network
    depends_on:
      - db

volumes:
  user_pgdata:
  user_pgadmin-data:

networks: 
  gameradar-network:
    driver: bridge
    external: true # to use an external network

# ${DB_USERNAME}
